tango_with_django_project/rango/urls.py
from django.urls import path,include
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    #path('register/', views.register, name='register'),
    #path('login/', views.user_login, name='login'),
    # path('restricted/', views.restricted, name='restricted'),
    #path('logout/', views.user_logout, name='logout'),
    path('movielist/', views.show_movies, name='show_movies'),
    path('moviedetail/<str:movieid>/', views.movie_detail, name='movie_detail'),
    #path('accounts/', include('allauth.urls')),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('addmovie/', views.ColMovie.as_view()),
    path('likemovie/', views.LikeMovie.as_view()),
    path('watchlist/',views.MyWatchList,name="watchlist"),
    path('likedlist/',views.MyLikedMovies,name="likedlist"),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('thank_you/', views.thank_you, name='thank_you'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # 3 - The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('oauth/', include('social_django.urls', namespace='social')), 
    path('accounts/', include('registration.backends.simple.urls')),
    path('googlelog/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

#model to store the entire list of all available disney movies
class MovieLists(models.Model):
    movieid=models.CharField(primary_key=True,max_length=15,unique=True)
    title=models.CharField(max_length=120,unique=False)
    fullTitle=models.CharField(max_length=250,unique=False)
    yearreleased=models.IntegerField(null=True)
    imgpath=models.CharField(max_length=400)
    imdbrating=models.FloatField(null=True)
    description=models.CharField(max_length=250,unique=False)

    class Meta:
      ordering = ['-movieid']


class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
#model for user profile
class UserProfile(models.Model):
    #each user has its own profile
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(default=10,null=False)
    location = models.CharField(max_length=150,null=False)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username
#model for moviecollection
class MovieCol(models.Model):
    #a user can have many collected movies
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    #a movie can be collected by many collections
    movie=models.ForeignKey(MovieLists,on_delete=models.CASCADE)
        
    class Meta:
        verbose_name='Movie collection'
        verbose_name_plural=verbose_name
#model for movie get liked
class MovieLiked(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    movie=models.ForeignKey(MovieLists,on_delete=models.CASCADE)
    class Meta:
        verbose_name='Movie liked'
        verbose_name_plural=verbose_name
class WebsiteLiked(models.Model):
    likes=models.IntegerField(default=0)
    id=models.IntegerField(primary_key=True)
    class Meta:
        verbose_name='Web liked'
        verbose_name_plural=verbose_name

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import widgets
from rango.models import MovieCol, Page, Category, UserProfile

# We could add these forms to views.py, but it makes sense to split them off into their own file.

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class MovieListForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        fields = ('name',)        

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):

    
    class Meta:
        model = UserProfile
        fields = ('picture','location','age')

        # widget={
        #     'picture':forms.TextInput(attrs={'class':'form-control'}),
        #     'location':forms.TextInput(attrs={'class':'form-control'}),
        #     'age':forms.NumberInput(attrs={'class':'form-control'})
        # }

tango_with_django_project/rango/views.py
from collections import namedtuple
from django.core import paginator
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.models import Category, MovieLists, Page, UserProfile,MovieCol,MovieLiked,WebsiteLiked
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from datetime import datetime
from django.core.paginator import PageNotAnInteger, Paginator,EmptyPage
import requests
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.views import View

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    context_dict['extra'] = 'From the model solution on GitHub'
    
    visitor_cookie_handler(request)

    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)

def thank_you(request):

    return render(request, 'rango/thank_you.html')

def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
    
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None
    
    # You cannot add a page to a Category that does not exist... DM
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)  # This could be better done; for the purposes of TwD, this is fine. DM.
    
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits

#This function fetches the entire list of movies for a logged in user
@login_required
def show_movies(request):
    fileredpage =""
    if 'q' in request.GET:
        q=request.GET['q']
        #if read from the database, order the movie by its imdbrating
        fileredpage=MovieLists.objects.filter(title__icontains=q).order_by('-imdbrating')
        print(q)   
    else:
        fileredpage=MovieLists.objects.all().order_by('-imdbrating')

   #make sure it reads from the API when the database is empty
    if(MovieLists.objects.count()==0):
        result = requests.get('https://imdb-api.com/en/API/IMDbList/k_6x2ikd97/ls004285275')
        myjson=result.json()
        

        MovieLists.objects.all().delete()
    
        for item in myjson['items']:
            MovieLists.objects.create(movieid=item['id'], 
            title=item['title'], fullTitle=item['fullTitle'], 
            yearreleased=item['year'], imgpath=item['image'],
            imdbrating=item['imDbRating'],description=item['description'])

            
        myresult = {"count": MovieLists.objects.count(), "page": MovieLists.objects.all().values()}
    
    else:
        myresult=fileredpage
       
       #code for pagination
        paginator=Paginator(myresult,16)
        page=request.GET.get('page')

        try:
            page = paginator.page(page)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page=paginator.page(paginator.num_pages) 
    
        myresult ={
        'count':paginator.count,
        'page': page
        } 

    return render(request, 'rango/movie_mini.html',  myresult )
  
  

#This function fetches the selected movie detail information for a authenticated user
@login_required
def movie_detail(request,movieid):
      print(request.user)
      movie=MovieLists.objects.get(movieid=movieid)
      movie.save()
      username = request.POST.get('username')  
      myresult ={
       'username': username,
       'movie': movie
     } 
      return render(request, 'rango/movie_detail.html',  myresult )

class RegisterProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)

    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'picture': user_profile.picture},
                                {'age': user_profile.age},
                                {'location': user_profile.location})
        
        return (user, user_profile, form)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        
        return render(request, 'rango/profile.html', context_dict)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'rango/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:profile',
                                    kwargs={'username': username}))
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'rango/profile.html', context_dict)

class ColMovie(View):
    @method_decorator(login_required)
    def post(self,request):
        if not request.user.is_authenticated:
            return render(request,'login.html')
        #get the movie_id from the front end
        movie_id=request.POST.get("movie_id")
        print(movie_id)
        find_movies=MovieCol.objects.filter(user=request.user,movie_id=movie_id).count()
        print(find_movies)
        #if haven't add this movie then push it to the database
        if find_movies<1:
            print(find_movies)
            fav_movie=MovieCol(user=request.user,movie_id=movie_id)
            fav_movie.save()
        #if =1 means there is already one been created
        else:
            #remove from database if already add this movie

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
<h1>Add a Category</h1>
<div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
    </form>
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
<h1>Add a Page to {{ category.name }}</h1>
<div>
    <form id="add_page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
        {% csrf_token %}
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Add Page" />
    </form>
</div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'rango_style.css' %}">
        <meta charset="UTF-8" />
        <title>
            {% block title_block %}
                Disney Fan Club
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        <div> 
            {% include 'rango/header.html' %}
        {% block body_block %}
        {% endblock %}
        <div class="clear"></div>
        {% include 'rango/footer.html' %}
        </div>


   

</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">  
            function homepageLogo() {
                document.getElementById("homepagelink").innerHTML = "<a href={% url 'rango:index' %}></a>";
            }
        </script>
        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>
     {% block js%}{% endblock %}
    </body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
        {% else %}
        <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/footer.html
<footer class="footer">
   <div class="footerContent">
   @Copyright 2021 Made by The Young Team 
</div>
</footer>

tango_with_django_project/templates/rango/header.html
{% load staticfiles %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

      <a class="navbar-brand" href="#">
        <div class="header_image">
        <img src="{% static 'images/icons8-disney-movies.svg' %}" height="65px" >
        DisneyFanClub
        </img>
        </div>
        </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">

          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:show_movies' %}">Movies</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:watchlist' %}">Watchlist</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:likedlist' %}">My Liked Movies</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
      {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
      {% endif %}
    
          
      </ul>
        </ul>
      </div>
      {% if user.is_authenticated %}
      <div class="usernameDetails">Welcome {{ user.username }}</div>
      {% endif %}
    </div>
  </nav>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
<div class="index_space">
    <p></p>
</div>
<div class="welcome_box">
    <p></p>
    {% if user.is_authenticated %}
    <div class="major">
        Welcome back {{ user.username }}!
    </div>
    <div class="central_image">
    <img src="{% static 'images/icons8-disney-movies.svg' %}" width="800" height="500" alt="Disney Fan Club Logo">
    </div>
    <div class="like_about">
        <a href="{% url 'rango:about' %}">Like Our Website</a>
    </div>
        <div class="image_1">
            <img src="{% static 'images/disney_castle.jpg' %}" width="200" height="150" alt="A Picture of the Disney World Castle" />
        </div>
        <div class="image_2">
            <img src="{% static 'images/disney_castle_general.jpg' %}" width="200" height="160" alt="A Picture of the Disney World Castle" />
        </div>
        <div class="image_3">
            <img src="{% static 'images/The_Great_Movie_Ride.jpg' %}" width="200" height="150" alt="A Picture outside of The Great Movie Ride" />
        </div>
        <div class="image_4">
            <img src="{% static 'images/Disneys_All_Star_Movies_Fantasia.jpg' %}" width="200" height="150" alt="Disney's All Star Movies Hotel" />
        </div>
    {% else %}
    <div class="image_1">
        <img src="{% static 'images/disney_castle.jpg' %}" width="200" height="150" alt="A Picture of the Disney World Castle" />
    </div>
    <div class="image_2">
        <img src="{% static 'images/disney_castle_general.jpg' %}" width="200" height="160" alt="A Picture of the Disney World Castle" />
    </div>
    <div class="image_3">
        <img src="{% static 'images/The_Great_Movie_Ride.jpg' %}" width="200" height="150" alt="A Picture outside of The Great Movie Ride" />
    </div>
    <div class="image_4">
        <img src="{% static 'images/Disneys_All_Star_Movies_Fantasia.jpg' %}" width="200" height="150" alt="Disney's All Star Movies Hotel" />
    </div>
    <div class="major">
        Welcome
    </div>
    <div class="medium">
    to 
    </div>
    <div class="medium">
        Disney Fan Club
    </div>
    <p></p>
    <div class="minor">
    the ultimate fan community!
    </div>
    {% endif %}
    <br />
</div>
{% endblock %}

tango_with_django_project/templates/rango/likedlist.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    WatchList
{% endblock %}

{% block body_block %}
<div class="container">
<ul class="list-group list-group-numbered">
{% for page in like_movies %}
<li class="list-group-item">
<label>{{page.movie.title}}</label>
</li>
{% endfor %}
</ul>
</div>
{% endblock %}

tango_with_django_project/templates/rango/query.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Movie Results
{% endblock %}

{% block body_block %}

{% if user.is_authenticated %}
       <div class="container-fluid"> 
{{myresult}}
        </div>
        {% endif %}

        {% endblock %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
<h1>Restricted Page</h1>
Since you're logged in, you can see this text!<br />
David was here!
{% endblock %}

tango_with_django_project/templates/rango/thank_you.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Like Our Website
{% endblock %}

{% block body_block %}
<h1>Like Our Website</h1>
<div>
    <h1>Thank you for liking our site!</h1>
    <strong id="like_count">{{ category.likes }}</strong> likes
</div>
{% endblock %}

tango_with_django_project/templates/rango/watchlist.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    WatchList
{% endblock %}

{% block body_block %}
<!-- Search Section -->
<div class="container py-5">
    <div class="row">
        <div class="col-md-8 offset-2">
            <form>
                <div class="input-group">
                    <input type="text" name="q" class="form-control form-control-lg" placeholder="Search" />
                    <div class="input-group-append">
                    <button class="btn btn-dark btn-lg" type="submit" id="button-addon2">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>
  
         <div class="container-fluid"> 
             <div class="row cardMain">
                    {% for page in col_movies %}
                      <div class="col-md-3">
                        <div class="card">
                        <img src={{page.movie.imgpath}} alt="movie picture" class="card-image-body">
                        <div class="card-body">
                          <div><label class="movieDetailLabel">Title : {{ page.movie.title}} </label></div>
                           <div>  <label class="movieDetailLabel">IMDB Rating : {{ page.movie.imdbrating}}</label> </div>
                           <div> <label class="movieDetailLabel">Year Released: {{ page.movie.yearreleased}} </label></div>
                      </div>
                       <a href="{%url 'rango:movie_detail' page.movie.movieid  %}" class="viewmore">View More</a>
                  </div>
              </div>
              {% endfor %}
              
         
              </div>
              <div class="pagination-container">
              <nav aria-label="...">
              {% if page.has_other_pages %}
              <ul class="pagination">
             {% if page.has_previous %}
               <li class="page-item"><a class="page-link"  href="?page={{ page.previous_page_number }}">«</a></li>
             {% else %}
               <li class="disabled"><span>Previous</span></li>
             {% endif %}
             {% for i in page.paginator.page_range %}
               {% if page.number == i %}
              <li class="page-item active">
                <a class="page-link" href="#">{{ i }} </a>
               {% else %}
               <li class="page-item"><a  class="page-link" href="?page={{ i }}">{{ i }}</a></li>
               {% endif %}
             {% endfor %}
             {% if page.has_next %}
             <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
             {% else %}
               <li class="disabled"><span>»</span></li>
             {% endif %}
              </ul>
            {% endif %}
            </nav>
          </div>
            </div>
{% endblock %}